# .github/workflows/main.yml

name: Merge test 2
on:
  push
jobs:
  merge:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - name: Merge upstream 2
        run: |
          git config --global user.name 'mastroja'
          git config --global user.email 'mastroiannij1@gmail.com'

          # "git checkout master" is unnecessary, already here by default
          git pull --unshallow  # this option is very important, you would get
                                # complains about unrelated histories without it.
                                # (but actions/checkout@v2 can also be instructed
                                # to fetch all git depth right from the start)

          git remote add upstream https://github.com/OpenSystems-CCHMC/test-host
          git fetch upstream

          git checkout -b sync-"$(date +"%D_%T")"
          git merge --no-edit upstream/main
          git checkout -b sync-"$(date +"%D_%T")"

          # git checkout main
          # git merge --no-edit upstream/main
          # git push origin main

          # etc
