# .github/workflows/main.yml

name: Merge test
on:
  push
jobs:
  merge:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v2
        with:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
      - name: Merge upstream
        run: |
          git config --global user.name 'mastroja'
          git config --global user.email 'mastroiannij1@gmail.com'

          # "git checkout master" is unnecessary, already here by default
          git pull --unshallow  # this option is very important, you would get
                                # complains about unrelated histories without it.
                                # (but actions/checkout@v2 can also be instructed
                                # to fetch all git depth right from the start)

          git remote add upstream https://github.com/OpenSystems-CCHMC/test-host
          git fetch upstream

          git checkout -b Fork_sync
          git merge --no-edit upstream/main
          git push origin main
          gh pr create --base main --head Fork_sync
         

          # git checkout main
          # git merge --no-edit upstream/main
          # git push origin main

          # etc
